# Generated by Django 4.0 on 2021-12-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RusChineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(max_length=1023)),
                ('chine', models.CharField(max_length=1023)),
            ],
        ),
    ]
